### ISSUE TITLE
Question: Is it possible to write to a Rekordbox library with this?

### ISSUE THREAD

**Issue by MichelJonkman** [Holzhaus/rekordcrate#108]
I'm looking for a tool that lets me automate some of my Rekordbox library stuff but I couldn't clearly see whether this library can only read or of it can also write back, at least to edit what song is in what playlist.

Even if it's not possible, thank you for making this!

**Comment by Swiftb0y** [comment]
It should be possible to a limited degree (we don't know enough about the format yet). Since we read in the entire database and then write it out, its not really possible to just make "small incisions" (like editing what song is in what playlist). We don't know enough about the underlying format yet to be confident enough that the resulting database will always be recognized by the players, so use at your own risk.

**Comment by MichelJonkman** [comment]
So it is possible but there's a potential for data loss?

**Comment by Swiftb0y** [comment]
Yes. At least we can't give any guarantees as of right now whether the produced `.pdb`s will get accepted by rekordbox or CDJs.

**Comment by MichelJonkman** [comment]
Alright, I'll keep that in mind!
